_target_: sri_maper.src.data.preprocessing.generate_raster_stacks
raster_stacks:
  - raster_stack_path: ${data.tif_dir}/umidwest_mamanico_d${data.window_size}.tif
    raster_files_path: ${paths.data_dir}/raster_libraries/umidwest_mamanico_raster_library
    dilation_size: ${data.window_size}
    outlier_removal: false
    raster_files:
      - "Geophysics/Seismic/Geophysics_LAB.tif"
      - "Geophysics/Seismic/Geophysics_LAB_HGM.tif"
      - "Geophysics/Seismic/Geophysics_LAB_HGM_Worms.tif"
      - "Geophysics/Seismic/Geophysics_Moho.tif"
      - "Geophysics/Gravity/Geophysics_Satellite_Gravity.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_HGM.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_HGM_Worms.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_Up30km.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_Up30km_HGM.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_Up30km_HGM_Worms.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Isostatic.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Isostatic_HGM.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Isostatic_HGM_Worms.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_HGM.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_HGM_Worms.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_Long-Wavelength.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_Long-Wavelength_HGM.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_Long-Wavelength_HGM_Worms.tif"
      - "Geophysics/MT/Geophysics_MT2023_9km.tif"
      - "Geophysics/MT/Geophysics_MT2023_15km.tif"
      - "Geophysics/MT/Geophysics_MT2023_30km.tif"
      - "Geophysics/MT/Geophysics_MT2023_48km.tif"
      - "Geophysics/MT/Geophysics_MT2023_92km.tif"
      - "Geophysics/Radiometric/Geophysics_Radiometric_Uranium.tif"
      - "Geophysics/Radiometric/Geophysics_Radiometric_Potassium.tif"
      - "Geophysics/Radiometric/Geophysics_Radiometric_Thorium.tif"
      - "Labels/national_mama_nico_deposits_umidwest.tif"
    raster_files_types:
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - bool
