_target_: sri_maper.src.data.preprocessing.generate_raster_stacks
raster_stacks:
  - raster_stack_path: ${data.tif_dir}/mvt_sigspatial_aus_d${data.window_size}.tif
    raster_files_path: ${paths.data_dir}/raster_libraries/SIGSPATIAL_raster_library/aus
    dilation_size: ${data.window_size}
    outlier_removal: true
    raster_files:
      - "Geochemistry_BlackShales_Proximity_clipped.tif"
      - "Geology_Faults_Proximity_clipped.tif"
      - "Geology_Igneous_Dictionaries_clipped.tif"
      - "Geology_Lithology_Majority_Igneous_Extrusive_clipped.tif"
      - "Geology_Lithology_Majority_Igneous_Intrusive_Felsic_clipped.tif"
      - "Geology_Lithology_Majority_Igneous_Intrusive_Mafic_clipped.tif"
      - "Geology_Lithology_Majority_Metamorphic_Gneiss_clipped.tif"
      - "Geology_Lithology_Majority_Metamorphic_Gneiss_Paragneiss_clipped.tif"
      - "Geology_Lithology_Majority_Metamorphic_Schist_clipped.tif"
      - "Geology_Lithology_Majority_Other_Unconsolidated_clipped.tif"
      - "Geology_Lithology_Majority_Sedimentary_Chemical_clipped.tif"
      - "Geology_Lithology_Majority_Sedimentary_Siliciclastic_clipped.tif"
      - "Geology_Lithology_Minority_Igneous_Extrusive_clipped.tif"
      - "Geology_Lithology_Minority_Igneous_Intrusive_Felsic_clipped.tif"
      - "Geology_Lithology_Minority_Igneous_Intrusive_Mafic_clipped.tif"
      - "Geology_Lithology_Minority_Metamorphic_Gneiss_clipped.tif"
      - "Geology_Lithology_Minority_Metamorphic_Gneiss_Paragneiss_clipped.tif"
      - "Geology_Lithology_Minority_Metamorphic_Schist_clipped.tif"
      - "Geology_Lithology_Minority_Other_Unconsolidated_clipped.tif"
      - "Geology_Lithology_Minority_Sedimentary_Chemical_clipped.tif"
      - "Geology_Lithology_Minority_Sedimentary_Siliciclastic_clipped.tif"
      - "Geology_Metamorphic_Dictionaries_clipped.tif"
      - "Geology_Paleolatitude_Period_Minimum_clipped.tif"
      - "Geology_PassiveMargins_Proximity_clipped.tif"
      - "Geology_Period_Maximum_Majority_clipped.tif"
      - "Geology_Period_Minimum_Majority_clipped.tif"
      - "Geology_Sedimentary_Dictionaries_clipped.tif"
      - "Geology_TerraneBoundaries_Proximity_clipped.tif"
      - "Geophysics_Gravity_Bouguer_clipped.tif"
      - "Geophysics_Gravity_Bouguer_HGM_clipped.tif"
      - "Geophysics_Gravity_Bouguer_HGM_Worms_clipped.tif"
      - "Geophysics_Gravity_Bouguer_Up30km_HGM_clipped.tif"
      - "Geophysics_Gravity_Bouguer_Up30km_HGM_Worms_clipped.tif"
      - "Geophysics_LAB_clipped.tif"
      - "Geophysics_Mag_RTP_HGM_clipped.tif"
      - "Geophysics_Mag_RTP_HGM_Worms_clipped.tif"
      - "Geophysics_Mag_RTP_Long-Wavelength_HGM_clipped.tif"
      - "Geophysics_Mag_RTP_Long-Wavelength_HGM_Worms_clipped.tif"
      - "Geophysics_Moho_clipped.tif"
      - "Geophysics_Satellite_Gravity_clipped.tif"
      - "mvt_deposits_clipped.tif"
    raster_files_types:
      - float32
      - float32
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - float32
      - float32
      - float32 #"Geology_Period_Maximum_Majority_clipped.tif"
      - float32 #"Geology_Period_Minimum_Majority_clipped.tif"
      - bool
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - bool
