_target_: sri_maper.src.data.preprocessing.generate_raster_stacks
raster_stacks:
  - raster_stack_path: ${data.tif_dir}/mvt-natl_d${data.window_size}.tif
    raster_files_path: ${paths.data_dir}/raster_libraries/national_scale_raster_library
    dilation_size: ${data.window_size}
    outlier_removal: false
    raster_files:
      - "Geology/Geology_Lithology_Majority_Igneous_Extrusive_clipped.tif"
      - "Geology/Geology_Lithology_Majority_Igneous_Intrusive_Felsic_clipped.tif"
      - "Geology/Geology_Lithology_Majority_Igneous_Intrusive_Mafic_clipped.tif"
      - "Geology/Geology_Lithology_Majority_Metamorphic_Gneiss_clipped.tif"
      - "Geology/Geology_Lithology_Majority_Metamorphic_Gneiss_Paragneiss_clipped.tif"
      - "Geology/Geology_Lithology_Majority_Metamorphic_Schist_clipped.tif"
      - "Geology/Geology_Lithology_Majority_Other_Unconsolidated_clipped.tif"
      - "Geology/Geology_Lithology_Majority_Sedimentary_Chemical_clipped.tif"
      - "Geology/Geology_Lithology_Majority_Sedimentary_Siliciclastic_clipped.tif"
      - "Geology/Geology_Lithology_Minority_Igneous_Extrusive_clipped.tif"
      - "Geology/Geology_Lithology_Minority_Igneous_Intrusive_Felsic_clipped.tif"
      - "Geology/Geology_Lithology_Minority_Igneous_Intrusive_Mafic_clipped.tif"
      - "Geology/Geology_Lithology_Minority_Metamorphic_Gneiss_clipped.tif"
      - "Geology/Geology_Lithology_Minority_Metamorphic_Gneiss_Paragneiss_clipped.tif"
      - "Geology/Geology_Lithology_Minority_Metamorphic_Schist_clipped.tif"
      - "Geology/Geology_Lithology_Minority_Other_Unconsolidated_clipped.tif"
      - "Geology/Geology_Lithology_Minority_Sedimentary_Chemical_clipped.tif"
      - "Geology/Geology_Lithology_Minority_Sedimentary_Siliciclastic_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Cambrian_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Cretaceous_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Devonian_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Jurassic_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Mesoproterozoic_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Mississippian_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Neoarchean_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Neogene_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Neoproterozoic_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Ordovician_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Paleogene_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Paleoproterozoic_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Pennsylvanian_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Permian_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Quaternary_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Silurian_clipped.tif"
      - "Geology/Geology_Period_Maximum_Majority_Triassic_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Cambrian_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Cretaceous_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Devonian_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Jurassic_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Mesoproterozoic_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Mississippian_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Neoarchean_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Neogene_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Neoproterozoic_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Ordovician_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Paleogene_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Paleoproterozoic_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Pennsylvanian_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Permian_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Quaternary_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Silurian_clipped.tif"
      - "Geology/Geology_Period_Minimum_Majority_Triassic_clipped.tif"
      - "Geology/Geology_Sedimentary_Dictionaries_clipped.tif"
      - "Geology/Geology_Igneous_Dictionaries_clipped.tif"
      - "Geology/Geology_Metamorphic_Dictionaries_clipped.tif"
      - "Geology/Geology_Paleolatitude_Period_Minimum_clipped.tif"
      - "Geology/Geology_TerraneBoundaries_Proximity_clipped.tif"
      - "Geology/Geology_PassiveMargins_Proximity_clipped.tif"
      - "Geology/Geology_Faults_Proximity_clipped.tif"
      - "Geophysics/Seismic/Geophysics_LAB_clipped.tif"
      - "Geophysics/Seismic/Geophysics_Moho_clipped.tif"
      - "Geophysics/Radiometric/Geophysics_Radiometric_Uranium_clipped.tif"
      - "Geophysics/Radiometric/Geophysics_Radiometric_Potassium_clipped.tif"
      - "Geophysics/Radiometric/Geophysics_Radiometric_Thorium_clipped.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_HGM_clipped.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_HGM_Worms_clipped.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_Long-Wavelength_HGM_clipped.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_Long-Wavelength_HGM_Worms_clipped.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_clipped.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_HGM_clipped.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_HGM_Worms_clipped.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_Up30km_HGM_clipped.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_Up30km_HGM_Worms_clipped.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Isostatic_clipped.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Isostatic_HGM_clipped.tif"
      - "Geophysics/Gravity/Geophysics_Satellite_Gravity_clipped.tif"
      - "Geochemistry/Geochemistry_BlackShales_Proximity_clipped.tif"
      - "Labels/mvt_leadzinc_sites_cont_US_clipped.tif"
      # - "Labels/mvt_leadzinc_sites_cont_US_clipped.tif"
    raster_files_types:
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - bool
