_target_: sri_maper.src.data.preprocessing.generate_raster_stacks
raster_stacks:
  - raster_stack_path: ${data.tif_dir}/mvt-h3_aoi_1_d${data.window_size}.tif
    raster_files_path: ${paths.data_dir}/raster_libraries/h3_aoi_1_mvt_raster_library
    dilation_size: ${data.window_size}
    outlier_removal: false
    raster_files:
      - "CEUS_GRAV_Isostatic_CEUSSSC_R0_clipped.tif"
      - "CEUS_GRAV_RI_1VD_CEUSSSC_R0_clipped.tif"
      - "CEUS_GRAV_RI_CEUSSSC_R0_clipped.tif"
      - "CEUS_GRAV_RI_HD_1VD_CEUSSSC_R0_clipped.tif"
      - "CEUS_GRAV_RI_HD_CEUSSSC_R0_clipped.tif"
      - "CEUS_MAG_DRTP_CEUSSSC_R0_clipped.tif"
      - "CEUS_MAG_DRTP_HD_TDR_CEUSSSC_R0_clipped.tif"
      - "CEUS_MAG_DRTP_TDR_CEUSSSC_R0_clipped.tif"
      - "CEUS_MAG_TMAG_AAS_CEUSSSC_R0_clipped.tif"
      - "Geophysics_LAB_HGM_clipped.tif"
      - "Geophysics_LAB_clipped.tif"
      - "Geophysics_Mag_RTP_Long-Wavelength_HGM_clipped.tif"
      - "Geophysics_Moho_clipped.tif"
      - "Geophysics_LAB_HGM_Worms.tif"
      - "Geophysics_Mag_RTP_Long-Wavelength_HGM_Worms.tif"
      # label
      - "mvt_leadzinc_deposits_h3_aoi_1.tif"
    raster_files_types:
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - bool
