_target_: sri_maper.src.data.preprocessing.generate_raster_stacks
raster_stacks:
  - raster_stack_path: ${data.tif_dir}/mvt-smidcont.tif
    raster_files_path: ${paths.data_dir}/mvt_regional_baseline1_raster_library
    dilation_size: ${data.window_size}
    raster_files:
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_smidcont_dilated.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_HGM_smidcont_dilated.tif"
      - "Labels/mvt_leadzinc_sites_smidcont_dilated.tif"
    raster_files_types:
      - float32
      - float32
      - bool
