_target_: sri_maper.src.data.preprocessing.generate_raster_stacks
raster_stacks:
  - raster_stack_path: ${data.tif_dir}/porphyry-copper-natl_d${data.window_size}.tif
    raster_files_path: ${paths.data_dir}/raster_libraries/national_scale_raster_library
    dilation_size: ${data.window_size}
    outlier_removal: true
    raster_files:
      - "Geophysics/Seismic/Geophysics_LAB_clipped.tif"
      - "Geophysics/Seismic/Geophysics_LAB_HGM_clipped.tif"
      - "Geophysics/Seismic/Geophysics_LAB_HGM_Worms_clipped.tif"
      - "Geophysics/Seismic/Geophysics_Moho_clipped.tif"
      - "Geophysics/Gravity/Geophysics_Satellite_Gravity_clipped.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_Up30km_HGM_clipped.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_Up30km_HGM_Worms_clipped.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Isostatic_clipped.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_clipped.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_LOGAnalyticSignal_clipped.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_Long-Wavelength_HGM_clipped.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_Long-Wavelength_HGM_Worms_clipped.tif"
      - "Geophysics/MT/Geophysics_MT2023_9km_clipped.tif"
      - "Geophysics/MT/Geophysics_MT2023_15km_clipped.tif"
      - "Geophysics/MT/Geophysics_MT2023_30km_clipped.tif"
      - "Geophysics/Radiometric/Geophysics_Radiometric_Potassium_clipped.tif"
      - "Geophysics/Radiometric/Geophysics_Radiometric_Thorium_clipped.tif"
      - "Geophysics/Radiometric/Geophysics_Radiometric_Uranium_clipped.tif"
      # - "Geochemistry/"
      # - "Geochemistry/"
      - "Geology/Geology_Lithology_Intrusive_Plutonic_Rock_Proximity_clipped.tif"
      - "Geology/Geology_Lithology_Extrusive_Volcanic_Rock_Proximity_clipped.tif"
      - "Geology/Geology_Age_Minimum_clipped.tif"
      - "Geology/Geology_Age_Maximum_clipped.tif"
      - "Labels/porphyry_copper_sites_cont_US_clipped.tif"
    raster_files_types:
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - bool
