_target_: sri_maper.src.models.cma_module_pretrain_mae.SSCMALitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-3
  weight_decay: 1e-2

scheduler:                                                                                                                        
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau                                                                            
  _partial_: true                                                                                                                 
  mode: min                                                                                                                       
  factor: 0.1                                                                                                                     
  patience: 10

net:
  _target_: sri_maper.src.models.mae_vit.MAE_ViT
  image_size: ${data.window_size}
  patch_size: 1
  input_dim: 14
  enc_dim: 256
  encoder_layer: 6
  encoder_head: 8
  dec_dim: 128
  output_dim: ${model.net.input_dim}
  decoder_layer: 2
  decoder_head: 4
  mask_ratio: 0.75

# compile model for faster training with pytorch 2.0
compile: false

mc_samples: 100

warmup_epoch: 1