_target_: sri_maper.src.models.cma_module.CMALitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-3
  weight_decay: 1e-2

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: sri_maper.src.models.mae_vit_classifer.CLSClassifer
  backbone_ckpt: null
  backbone_net: null
  freeze_backbone: true
  dropout_rate: 0.0

# compile model for faster training with pytorch 2.0
compile: false

gain: 1.0

extract_attributions: ${enable_attributions}
mc_samples: 100

smoothing: 0.1
